### ISSUE TITLE
SHIFT - mx

### ISSUE THREAD

**Issue by maaduukaar** [vekexasia/dpos-tools-data#150]
https://github.com/vekexasia/dpos-tools-data/blob/9f484347ab02d7e8cc4815a6d11786fb8581287f/shift.yml#L27-L32

 ```
 -
    delegate: mx
    share: 80
    notes: "50% to voters, 25% to marketing, 5% to the team"
    website: http://telegra.ph/Vote-for-Mx-05-28
    payout:
      min: 0.1
      schedule: monthly
      addresses: 
        - 4446910057799968777S
-
```
